# Generated by Django 5.0 on 2024-08-06 08:51

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.CharField()),
                ('created', models.DateField(default=datetime.datetime(2024, 8, 6, 8, 51, 28, 768752, tzinfo=datetime.timezone.utc))),
                ('played', models.BooleanField(default=False)),
            ],
        ),
    ]
