# Generated by Django 5.0 on 2024-07-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('length', models.SmallIntegerField(help_text='Длительность в минутах', verbose_name='Длительность')),
                ('author', models.CharField(max_length=255)),
                ('seen', models.BooleanField(choices=[('WD', 'Watched'), ('UD', 'Unwatched')], default='UD', max_length=2)),
            ],
        ),
    ]
