# Generated by Django 5.0 on 2024-07-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='seen',
            field=models.CharField(choices=[('WA', 'Watched'), ('UN', 'Unwatched')], default='UN', max_length=2),
        ),
    ]
