# Generated by Django 5.0 on 2024-08-03 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='seen',
            new_name='status',
        ),
    ]
